SELECT apellido1 FROM empleado;
SELECT DISTINCT apellido1 FROM empleado;
SELECT * FROM empleado;
SELECT nombre, apellido1, apellido2 FROM empleado;
SELECT id_departamento FROM empleado;
SELECT DISTINCT id_departamento FROM empleado;
SELECT CONCAT (nombre, ' ', apellido1, ' ', apellido2) AS nombre_completo FROM empleado;
SELECT id, substr(nif,1,8) AS numero, substr(nif,9,1) AS letra FROM empleado;
SELECT nombre, presupuesto - gastos AS presupuesto_actual FROM departamento;
SELECT nombre, presupuesto - gastos AS presupuesto_actual FROM departamento ORDER BY presupuesto_actual ASC;
SELECT nombre FROM departamento ORDER BY nombre ASC;
SELECT nombre FROM departamento ORDER BY nombre DESC;
SELECT apellido1, apellido2, nombre FROM empleado ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT nombre, presupuesto FROM departamento ORDER BY presupuesto DESC LIMIT 3;
SELECT nombre, presupuesto FROM departamento ORDER BY presupuesto ASC LIMIT 3;
SELECT nombre, gastos FROM departamento ORDER BY gastos DESC LIMIT 2;
SELECT nombre, gastos FROM departamento ORDER BY gastos ASC LIMIT 2;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto >=150000;
SELECT nombre, gastos FROM departamento WHERE gastos <5000;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto>=100000 AND presupuesto<=200000;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto<100000 OR presupuesto>200000;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto BETWEEN 100000 AND 200000;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto NOT BETWEEN 100000 AND 200000;
SELECT nombre, presupuesto, gastos FROM departamento WHERE gastos > presupuesto; 
SELECT nombre, presupuesto, gastos FROM departamento WHERE gastos<presupuesto;
SELECT nombre, gastos, presupuesto FROM departamento WHERE gastos=presupuesto;
SELECT* FROM empleado WHERE apellido1 IS NULL OR apellido2 IS NULL;
SELECT* FROM empleado WHERE apellido2 IS NOT NULL;
SELECT* FROM empleado WHERE apellido2='López';
SELECT* FROM empleado WHERE apellido2='Díaz' OR apellido2='Moreno';
SELECT* FROM empleado WHERE apellido2 IN('Díaz','Moreno');
SELECT nombre, apellido1, apellido2, nif FROM empleado WHERE id_departamento=3;
SELECT nombre, apellido1, apellido2, nif FROM empleado WHERE id_departamento IN(2, 4, 5);
SELECT SUM(presupuesto) AS suma FROM departamento;
SELECT AVG(presupuesto) AS media FROM departamento;
SELECT MIN(presupuesto) AS minimo FROM departamento;
SELECT MAX(presupuesto) AS maximo FROM departamento;
SELECT COUNT(nombre) AS cantidad FROM empleado;
SELECT COUNT(apellido2) AS cantidad FROM empleado WHERE apellido2 IS NOT NULL;
SELECT id_departamento, COUNT(nombre) FROM empleado GROUP BY id_departamento;
SELECT COUNT(*) FROM departamento WHERE presupuesto>gastos;
SELECT id_departamento, COUNT(*) FROM empleado WHERE nombre LIKE '%a%' GROUP BY id_departamento;
SELECT id_departamento, COUNT(*) FROM empleado GROUP BY id_departamento HAVING COUNT(*)>=2;
SELECT id_departamento FROM empleado WHERE apellido1 LIKE 'S%' OR apellido2 LIKE 'S%' GROUP BY id_departamento;
SELECT e.nombre, e.id_departamento, d.nombre AS nombre_departamento, d.presupuesto, d.gastos FROM empleado e JOIN departamento d ON e.id_departamento=d.id;
SELECT e.nombre, e.apellido1, e.apellido2, d.nombre AS nombre_departamento FROM empleado e JOIN departamento d ON e.id_departamento=d.id ORDER BY d.nombre ASC, e.apellido1 ASC, e.apellido2 ASC, e.nombre ASC;
SELECT DISTINCT d.id, d.nombre AS nombre FROM empleado e JOIN departamento d ON e.id_departamento=d.id;
SELECT DISTINCT d.id, d.nombre AS nombre, d.presupuesto - d.gastos AS presupuesto_actual FROM empleado e JOIN departamento d ON e.id_departamento=d.id;
SELECT d.nombre AS nombre FROM empleado e JOIN departamento d ON e.id_departamento=d.id WHERE e.nif='38382980M';
SELECT d.nombre AS nombre FROM empleado e JOIN departamento d ON e.id_departamento=d.id WHERE e.nombre='Pepe' AND e.apellido1='Ruiz' AND e.apellido2='Santana';
SELECT e.id, e.nif, e.nombre, e.apellido1, e.apellido2, e.id_departamento FROM empleado e JOIN departamento d ON e.id_departamento=d.id WHERE d.nombre= 'I+D' ORDER BY e.nombre ASC;
SELECT e.id, e.nif, e.nombre, e.apellido1, e.apellido2, e.id_departamento FROM empleado e JOIN departamento d ON e.id_departamento=d.id WHERE d.nombre IN ('I+D', 'Sistemas', 'Contabilidad') ORDER BY e.nombre ASC;
SELECT e.nombre FROM empleado e JOIN departamento d ON e.id_departamento=d.id WHERE NOT d.presupuesto between 100000 AND 200000;
SELECT DISTINCT d.nombre AS nombre FROM empleado e JOIN departamento d ON e.id_departamento=d.id WHERE apellido2 IS NULL;
SELECT e.nombre AS nombre, d.nombre AS nombre_departamento FROM empleado e LEFT JOIN departamento d ON e.id_departamento=d.id;
SELECT e.id, e.nif, e.nombre, e.apellido1, e.apellido2, e.id_departamento FROM empleado e LEFT JOIN departamento d ON e.id_departamento=d.id WHERE e.id_departamento IS NULL;
SELECT d.id, d.nombre, d.presupuesto, d.gastos FROM empleado e RIGHT JOIN departamento d ON e.id_departamento=d.id WHERE e.id_departamento IS NULL;