SELECT * FROM pedido ORDER BY fecha DESC;
SELECT * FROM pedido ORDER BY total DESC LIMIT 2;
SELECT DISTINCT id_cliente FROM pedido;
SELECT * FROM pedido WHERE YEAR(fecha)=2017 AND total>500;
SELECT nombre, apellido1, apellido2 FROM comercial WHERE comision BETWEEN 0.05 AND 0.11;
SELECT MAX(comision) AS maximo FROM comercial;
SELECT id, nombre, apellido1 FROM cliente WHERE apellido2 IS NOT NULL ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT nombre FROM cliente WHERE nombre LIKE 'A%n' OR nombre LIKE 'P%' ORDER BY nombre ASC;
SELECT nombre FROM cliente WHERE nombre NOT LIKE 'A%' ORDER BY nombre ASC;
SELECT DISTINCT nombre FROM comercial WHERE nombre LIKE '%el' OR nombre LIKE '%o';
SELECT SUM(total) AS total FROM pedido;
SELECT AVG(total) AS total FROM pedido;
SELECT COUNT(DISTINCT id_comercial) AS cantidad FROM pedido;
SELECT COUNT(nombre) AS cantidad FROM cliente;
SELECT MAX(total) AS maximo FROM pedido;
SELECT MIN(total) AS minimo FROM pedido;
SELECT ciudad, MAX(categoria) AS maximo FROM cliente GROUP BY ciudad;
SELECT id_cliente, fecha, MAX(total) FROM pedido GROUP BY id_cliente,fecha;
SELECT id_comercial, MAX(total) FROM pedido WHERE fecha='2016-08-17' GROUP BY id_comercial;
SELECT DISTINCT c.id, c.nombre, c.apellido1, c.apellido2 FROM cliente c JOIN pedido p ON p.id_cliente=c.id ORDER BY apellido1 ASC, apellido2 ASC;
SELECT co.id, co.nombre, co.apellido1, p.total FROM comercial co JOIN pedido p ON co.id=p.id_comercial WHERE co.nombre='Antonio';
SELECT c.* FROM cliente c JOIN pedido p ON p.id_cliente=c.id WHERE YEAR(fecha)=2017 AND total BETWEEN 300 AND 1000;
SELECT c.nombre, c.apellido1, c.apellido2, AVG(total) AS media FROM pedido p JOIN cliente c ON p.id_cliente=c.id GROUP BY c.nombre, c.apellido1, c.apellido2;
SELECT DISTINCT co.nombre, co.apellido1, co.apellido2 FROM comercial co JOIN pedido p ON co.id=p.id_comercial JOIN cliente cl ON p.id_cliente=cl.id WHERE cl.nombre='Pepe' AND cl.apellido1='Ruiz' AND cl.apellido2='Santana';
SELECT DISTINCT cl.nombre, cl.apellido1, cl.apellido2 FROM cliente cl JOIN pedido p ON p.id_cliente=cl.id JOIN comercial co ON p.id_comercial=co.id WHERE co.nombre='Daniel' AND co.apellido1='Sáez' AND co.apellido2='Vega';