SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio*1.10 FROM producto;
SELECT nombre AS nombre_producto, precio AS euros, precio*1.10 AS dolares FROM producto;
SELECT id_fabricante FROM producto;
SELECT DISTINCT id_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT * FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY PRECIO DESC LIMIT 1;
SELECT nombre FROM producto where id_fabricante=2;
SELECT nombre, precio FROM producto WHERE precio <=120;
SELECT nombre, precio FROM producto WHERE precio >=400;
SELECT nombre, precio FROM producto WHERE NOT precio >=400;
SELECT nombre, precio FROM producto WHERE precio>=80 AND precio<=300; 
SELECT nombre, precio FROM producto WHERE precio BETWEEN 60 AND 200;
SELECT * FROM producto WHERE precio >200 AND id_fabricante=6;
SELECT * FROM producto WHERE id_fabricante=1 OR id_fabricante=3 OR id_fabricante=5 ;
SELECT * FROM producto WHERE id_fabricante IN (1, 3, 5);
SELECT nombre, precio, precio*100 AS centimos FROM producto;
SELECT nombre FROM fabricante WHERE nombre LIKE 's%';
SELECT nombre FROM fabricante WHERE nombre LIKE '%e';
SELECT nombre FROM fabricante WHERE nombre LIKE '%w%';
SELECT nombre FROM fabricante WHERE nombre LIKE '____';
SELECT * FROM producto WHERE nombre LIKE '%Portátil%';
SELECT nombre, precio FROM producto WHERE nombre LIKE '%Monitor%' AND precio<215;
SELECT nombre, precio FROM producto WHERE precio>=180 ORDER BY precio DESC, nombre ASC;
SELECT COUNT(precio) AS cantidad FROM producto;
SELECT COUNT(nombre) AS cantidad FROM fabricante;
SELECT COUNT(DISTINCT id_fabricante) AS cant_id_fabricante FROM producto;
SELECT AVG(precio) AS media FROM producto;
SELECT MIN(precio) AS precio_barato FROM producto;
SELECT MAX(precio) AS precio_caro FROM producto;
SELECT SUM(precio) FROM producto;
SELECT AVG(precio) AS media, MIN(precio) AS barato, MAX(precio) AS caro FROM producto;
SELECT MAX(precio) AS maximo, MIN(precio) AS minimo, AVG(precio) AS medio, COUNT(precio) AS cantidad FROM producto WHERE id_fabricante=1;
SELECT AVG(precio) AS media FROM producto WHERE nombre LIKE '%Portátil%';
SELECT MAX(precio) AS maximo, MIN(precio) AS minimo FROM producto WHERE nombre LIKE '%Portátil%' OR nombre LIKE '%Monitor%';
SELECT id_fabricante, COUNT(nombre) AS cantidad FROM producto GROUP BY id_fabricante ORDER BY cantidad DESC;
SELECT id_fabricante, MAX(precio) AS maximo, MIN(precio) AS minimo, AVG(precio) AS media FROM producto GROUP BY id_fabricante;
SELECT id_fabricante, MAX(precio) AS maximo, MIN(precio) AS minimo, AVG(precio) AS media, COUNT(precio) AS cantidad FROM producto GROUP BY id_fabricante HAVING AVG(precio)>=200;
SELECT COUNT(nombre) AS cantidad FROM producto WHERE precio>=180;
SELECT id_fabricante, COUNT(nombre) FROM producto WHERE precio>=180 GROUP BY id_fabricante;
SELECT id_fabricante, AVG(precio) AS media FROM producto GROUP BY id_fabricante; 
SELECT p.nombre, precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id ORDER BY nombre_fabricante ASC;
SELECT p.id, p.nombre, f.id, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id ORDER BY precio ASC LIMIT 1;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id ORDER BY precio DESC LIMIT 1;
SELECT p.id, p.nombre, p.precio, p.id_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id WHERE f.nombre='Lenovo';
SELECT p.id, p.nombre, p.precio, p.id_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id WHERE f.nombre='Crucial' AND p.precio>200;
SELECT p.id, p.nombre, p.precio, p.id_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id WHERE f.nombre='Seagate' OR f.nombre='Asus' OR f.nombre='Hewlett-Packard';
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.id_fabricante=f.id WHERE f.nombre LIKE '%e';
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.id_fabricante=f.id WHERE f.nombre LIKE '%w%';
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.id_fabricante=f.id WHERE p.precio>=180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT DISTINCT f.id, f.nombre FROM producto p JOIN fabricante f ON p.id_fabricante=f.id;  
SELECT f.nombre AS nombre_fabricante, p.nombre FROM fabricante f LEFT JOIN producto p ON p.id_fabricante=f.id; 
SELECT f.id, f.nombre FROM producto p RIGHT JOIN fabricante f ON p.id_fabricante=f.id WHERE p.id_fabricante IS NULL;